### ISSUE TITLE
REPORTED: Delay(0) bug

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#157]
https://www.doomworld.com/forum/topic/93479-changed-delay0/

```
<Mordeth> you can test this yourself: measure a sector A light level in a loop, and adjust a different sector B to your A level
<Mordeth> in one loop you do delay(1); the other delay(0)
<Mordeth> if you make A blink, you'll notice that a rapid sequence of blinking will lag for sector B
<Mordeth> with delay(1)
<Mordeth> it does not with delay(0) (and will have rather poor performance)
```

**Comment by Altazimuth** [comment]
Given it's been clarified this is intended (as it's Hexen behaviour), should this issue be closed?

**Comment by ioan-chera** [comment]
Depends. Does it work for Mordeth exactly as described by DavidPH? Close it if so.

**Comment by Mordeth2** [comment]
You guys fail to understand the issue. It is not about delay(0) or delay(1) or how it is supposed to work. It's about the fact that polywait() *itself* seems to halt *regardless* of polyobject status whenever it is proceeded by a delay(). The specified delay(0) completely falls within the period in which that polyobject is still moving.  In other words, for that script the delay() does not matter because it is at polywait that the script is supposed to halt.

This is how it worked in previous versions;  a smooth continuous movement of the polyobjects. How it works after acsvm: always a halt in every iteration of the loop. The same map and same script behave differently before/after acsvm.

Easy to adjust for me; but this is proof that *something* has changed and it is probably unintentional.

**Comment by Altazimuth** [comment]
Commit 5a80aa9 should fix it, though we'll need Mordeth to test.

**Comment by ioan-chera** [comment]
Fixed (reported here: https://www.doomworld.com/forum/topic/93479-changed-delay0/?do=findComment&comment=1735643 )
