### ISSUE TITLE
"Sparklies" on textures with transparency

### ISSUE THREAD

**Issue by Blastfrog** [team-eternity/eternity#19]
I just noticed that the edges of pixels are sometimes filled with index 0, which is particularly noticeable using palettes with white instead of black as the first index.

**Comment by sneakernets** [comment]
I believe this is a precision issue. try reducing the screen size and see if it gets worse.

**Comment by Blastfrog** [comment]
Doesn't seem to get any worse or better. I notice it occurs the most at the very center of the view.

**Comment by sneakernets** [comment]
I'll try BOOMEDIT.wad and report back what I find.

**Comment by haleyjd** [comment]
It is a one-pixel overflow off the end of a masked column texture picking up the zero-filled backing of the linear texture buffer, caused by round-off error. This is the same issue which caused a crash in BSD for Ryan, but that was because it was happening at the end of the buffer and I extended the texture buffers as a "fix" to that problem since I couldn't figure out where the round-off error comes from or how to fix it.

**Comment by ioan-chera** [comment]
Happens both with r_columnengine (console variable) set to either "quad" or "normal".

**Comment by ioan-chera** [comment]
Reopened because of some unfixed side effects.

**Comment by ioan-chera** [comment]
Hopefully fixed.
