### ISSUE TITLE
[Feature Request] Add Secret Find Notification

### ISSUE THREAD

**Issue by sinisterseed** [team-eternity/eternity#336]
Basically what the title says.

We need a secret notification when finding messages, and I think the sound effect used by these 2 ports would also be the best choice for the sake of consistency across ports. Crispy uses the item respawn effect, but it's the only one doing so as far as I'm aware.

**Comment by ioan-chera** [comment]
Personally I'm not fond of that sound, it seems an artifact of ZDoom. Since it's mostly about style, I'd rather have a new sound for Eternity.

Personally I'm not fond of secret find notifications. Many times they're not even real secrets, such as e2m6 or e4m3. Let user look in the HUD for the secret score.

**Comment by sinisterseed** [comment]
> Personally I'm not fond of secret find notifications. Many times they're not even real secrets, such as e2m6 or e4m3. Let user look in the HUD for the secret score.

Well, it can always be a toggleable option of course :) .

I would've preferred the ZDoom sound for the sake of consistency across ports (it isn't the only one using it), but I'm just as fine with another.

**Comment by ioan-chera** [comment]
Actually let's close this.

**Comment by ioan-chera** [comment]
Resurrecting it because it can be managed and may help users.

**Comment by Altazimuth** [comment]
We could initiallly have no sound? Blood does it. (I take no credit for this, Dwars pointed it out.)

**Comment by sinisterseed** [comment]
> We could initiallly have no sound? Blood does it. (I take no credit for this, Dwars pointed it out.)

It depends on the implementation. I think a "soundless" approach could work just fine - but not if the message is going to be displayed the way it shows up in other ports, it feels like something's missing that way IMO.

[Doom 64 actually had secret notifications](https://www.youtube.com/watch?v=SEQvVSmYlHQ&t=354s) as far as I'm aware, it wasn't an EX feature, and its implementation was silent as well. You could try going for a D64-like approach (top-left corner, or even better, make it configurable, different color, that sort of thing).

**Comment by DwarsYT** [comment]
Some considerations for possibilities. The latest builds of the UMAPINFO fork of PrBoom+ also currently use the DSITMBK sound for its secret notification messages. If secret notifications is implemented in the ZDoom/Crispy/PrBoom+ style, ITMBK seems to be the more prevalent sound. Crispy also now implements CHAT for Heretic. At the very least, these'd probably be adequate filler sounds for single player since the sound is otherwise never (and for CHAT in Heretic, rarely) heard. I say filler because a new original sound could potentially be fashioned in the future, of course. Some level packs and mods have their own DSSECRET, which could probably be played instead if it's detected.

This is all of course considering that this would be an toggleable option in the menu, with the menu formula probably looking like so:
**Options**->Game Widgets->**HUD Settings**->Messages->**Display Secret Notifications - On/Off** _(Off by Default)_

**Comment by Gaerzi** [comment]
By the way, Strife does have a built-in secret notification sound. Though Strife support in Eternity is probably still a long way off.

**Comment by sinisterseed** [comment]
Since this popped up in my feed, well, I agree that since the ZDoom secret sfx has been purged from PrBoom along with the rest of the more dubious resources, my original idea falls flat, so maybe just use the multiplayer item respawn sfx to keep it consistent with the other ports instead, or something else entirely?

**Comment by DwarsYT** [comment]
Like I said before, if the secret notification is implemented in the ZDoom/Crispy/PrBoom+/etc. fashion, ITMBK and CHAT could be used as 'filler' noises to use once the feature is coded in until a proper DSSECRET sound is made. Though of course, an original sound doesn't HAVE to be made.

**Comment by ioan-chera** [comment]
@Altazimuth Do you think this is completed?

**Comment by Altazimuth** [comment]
Effectively. What's there could be improved a bit but it exists.
