### ISSUE TITLE
launching eternity Pi4

### ISSUE THREAD

**Issue by Exarkuniv** [team-eternity/eternity#475]
i was able to compile this on my Pi4 running buster just fine. but i cant get it to start. I dont have a desktop as im running RetroPie

when i run ``./eternity`` i get this

The Eternity Engine
Copyright 2020 James Haley, Stephen McGranahan, et al.
http://www.doomworld.com/eternity

This program is free software distributed under the terms of
the GNU General Public License. See the file "COPYING" for
full details. Commercial sale or distribution of this product
without its license, source code, and copyright notices is an
infringement of US and international copyright laws.

Z_Init: Init zone memory allocation daemon.
D_SetBasePath: base path does not exist.

i have tried this also ``./eternity -iwad /home/pi/eternity/build/source/doom1.wad``

with the same output.
Im sure im doing something wrong, but i cant figure it out

**Comment by Altazimuth** [comment]
You want to do `-base ../base` or similar. Basically you need to specify the location of the `base` directory that you can find in the root of the EE repo. Generally if you're sitting in a `build/source` since you used CMake then it'll probably be `../../base`. Won't close yet in case there's another issue with this, but it should just be that.

**Comment by Exarkuniv** [comment]
@Altazimuth thank you. that was it. 
ill leave it open for now as im playing around with things and whatnot. so i dont have to open a new ticket

**Comment by Exarkuniv** [comment]
so messing with it i see that i dont have a system.cfg in my  ~/.config/eternity/user/

not sure if its really needed or not. im messing with seeing what mods might work or not
