### ISSUE TITLE
Reported bug: EE crashing at low vertical resolutions

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#54]
https://www.doomworld.com/vb/eternity/86545-anything-between-200-and-240-lines-crashes/

**Comment by haleyjd** [comment]
VBuffer scaling code can't tolerate a width < 320 since it was built ground-up on an assumption it will only ever be scaling up. For now, pending future rewrites, this is fixed by not allowing construction of a subscreen43 aspect-ratio-correcting patch buffer if its width would be less than SCREENWIDTH.
